import { FormField } from "@/hooks/types";

export const bannerFormFields: FormField[] = [
  {
    type: "text",
    name: "title.en",
    required: true,
    label: "Banner Title (EN)",
    placeholder: "Enter the banner title in English (e.g., Summer Sale 2025)",
  },
  {
    type: "text",
    name: "title.ar",
    required: true,
    label: "Banner Title (AR)",
    placeholder: "أدخل عنوان البانر باللغة العربية",
  },
  {
    type: "number",
    name: "order",
    required: true,
    min: 0,
    label: "Display Order",
    placeholder: "Enter the banner display order (e.g., 1 for top priority)",
  },
  {
    type: "choose",
    name: "isActive",
    required: true,
    label: "Banner Status",
    placeholder: "Select banner visibility status",
    options: [
      { label: "Active", value: true },
      { label: "Inactive", value: false },
    ],
  },
  {
    type: "textarea",
    name: "description.en",
    rows: 7,
    label: "Banner Description (EN)",
    placeholder: "Provide a detailed description in English (max 250 characters)",
  },
  {
    type: "textarea",
    name: "description.ar",
    rows: 7,
    label: "Banner Description (AR)",
    placeholder: "قدم وصفًا تفصيليًا للبانر باللغة العربية",
  },
  {
    type: "file",
    name: "image",
    required: true,
    label: "Banner Image",
    placeholder: "Upload a high-quality image for the banner",
    accept: "image/*",
  },
];

export const videoFormFields: FormField[] = [
  {
    type: "number",
    name: "minAmount",
    required: true,
    label: "Minimum Amount",
    placeholder: "Enter minimum amount",
  },
  {
    type: "number",
    name: "maxAmount",
    required: true,
    label: "Maximum Amount",
    placeholder: "Enter maximum amount",
  },
  {
    type: "number",
    name: "duration",
    required: true,
    label: "Duration (in seconds)",
    placeholder: "Enter duration in seconds",
  },
  {
    type: "file",
    required: true,
    name: "imageUrl",
    label: "Image URL",
    placeholder: "Enter video poster image URL",
  },
  {
    type: "file",
    name: "video",
    isVideo: true,
    required: true,
    label: "Video URL",
  },
];

export const countryFormField: FormField[] = [
  {
    type: "text",
    name: "name",
    label: "Country Name",
    placeholder: "Enter the full country name (e.g., United States)",
    required: true,
  },
  {
    type: "text",
    name: "code",
    label: "Country Code",
    placeholder: "Enter the ISO country code (e.g., US, IN, UK)",
    required: true,
  },
];

export const stateFormField: FormField[] = [
  {
    options: [],
    required: true,
    type: "select",
    label: "Select Country",
    name: "countryId",
    placeholder: "Choose the country this state belongs to",
  },
  {
    type: "text",
    name: "name",
    label: "State/Province Name",
    placeholder: "Enter the state or province name (e.g., California)",
    required: true,
  },
  {
    type: "text",
    name: "code",
    label: "State/Province Code",
    placeholder: "Enter the state/province code (e.g., CA, MH)",
    required: true,
  },
];

export const cityFormField: FormField[] = [
  {
    options: [],
    required: true,
    type: "select",
    label: "Select Country",
    name: "countryId",
    placeholder: "Choose the country for this city",
  },
  {
    options: [],
    required: true,
    type: "select",
    label: "Select State/Province",
    name: "stateId",
    placeholder: "Choose the state/province for this city",
  },
  {
    type: "text",
    name: "name",
    label: "City Name",
    placeholder: "Enter the city name (e.g., Los Angeles)",
    required: true,
  },
];

export const paymentField: FormField[] = [
  {
    options: [
      { label: "pending", value: "Pending" },
      { label: "approved", value: "Approved" },
    ],
    type: "select",
    name: "status",
    required: true,
    label: "Select payment status",
    placeholder: "Choose payment status",
  },
  {
    type: "date",
    name: "processedAt",
    label: "Processed At",
    placeholder: "Select Date",
  },
  {
    rows: 1,
    name: "remark",
    widthFull: true,
    type: "textarea",
    label: "Remarks",
    placeholder: "Provide a short remarks about the Redeem Request",
  },
];

export const productType: FormField[] = [
  {
    name: "name.en",
    label: "Product Name (EN)",
    type: "text",
    placeholder: "Enter product name in English",
    required: true,
    maxLength: 150,
  },
  {
    name: "name.ar",
    label: "Product Name (AR)",
    type: "text",
    placeholder: "أدخل اسم المنتج باللغة العربية",
    required: true,
    maxLength: 150,
  },
  {
    name: "price",
    label: "Price",
    type: "number",
    placeholder: "Enter product price",
    required: true,
    min: 0,
  },
  {
    name: "rating",
    label: "Rating",
    type: "number",
    min: 0,
    max: 5,
    placeholder: "Enter rating (0 - 5)",
  },
  {
    name: "brand",
    label: "Brand",
    type: "select",
    options: [], // dynamically populated
    placeholder: "Select brand",
    required: true,
  },
  {
    name: "category",
    label: "Category",
    type: "select",
    options: [], // dynamically populated
    placeholder: "Select category",
    required: true,
  },
  {
    name: "subCategory",
    label: "Sub-Category",
    type: "select",
    options: [], // dynamically populated
    placeholder: "Select sub-category",
  },
  {
    rows: 1,
    name: "description.en",
    label: "Description (EN)",
    type: "textarea",
    placeholder: "Enter product description in English",
    required: false,
    maxLength: 500,
  },
  {
    rows: 7,
    name: "description.ar",
    label: "Description (AR)",
    type: "textarea",
    placeholder: "أدخل وصف المنتج باللغة العربية",
    required: false,
    maxLength: 500,
  },
  {
    type: "file",
    name: "image",
    required: true,
    accept: "image/*",
    label: "Product Image",
    placeholder: "Upload product image",
  },
];

export const queryField: FormField[] = [
  {
    options: [
      { label: "Pending", value: "Pending" },
      { label: "Rejected", value: "Rejected" },
      { label: "Resolved", value: "Resolved" },
    ],
    type: "select",
    name: "status",
    required: true,
    label: "Query Status",
    placeholder: "Select query status (Pending / Resolved / Rejected)",
  },
  {
    rows: 2,
    name: "response",
    type: "textarea",
    label: "Response",
    placeholder: "Write a brief response to address the query",
  },
];

export const testimonialField: FormField[] = [
  {
    name: "name.en",
    label: "Customer Name (English)",
    type: "text",
    required: true,
    placeholder: "Enter the customer's full name in English",
  },
  {
    type: "textarea",
    rows: 1,
    name: "feedback.en",
    label: "Customer Feedback (English)",
    required: true,
    placeholder: "Share the customer’s feedback in English",
  },
  {
    name: "name.ar",
    label: "Customer Name (Arabic)",
    type: "text",
    required: false,
    placeholder: "أدخل الاسم الكامل للعميل باللغة العربية",
  },
  {
    type: "textarea",
    rows: 1,
    name: "feedback.ar",
    label: "Customer Feedback (Arabic)",
    required: false,
    placeholder: "شارك رأي العميل أو التوصية باللغة العربية",
  },
  {
    type: "number",
    name: "rating",
    label: "Customer Rating",
    required: true,
    placeholder: "Provide a rating between 1 and 5",
    min: 1,
    max: 5,
  },
  {
    type: "choose",
    name: "isActive",
    label: "Visible on Website?",
    placeholder: "Choose whether to display this testimonial",
  },
  {
    type: "choose",
    name: "isVerified",
    label: "Verified Testimonial?",
    placeholder: "Mark testimonial as verified",
  },
  {
    type: "file",
    name: "image",
    label: "Customer Image",
    placeholder: "Upload the customer's profile picture (optional)",
    accept: "image/*",
  },
];

export const blogField: FormField[] = [
  {
    type: "text",
    name: "title",
    label: "Blog Title",
    required: true,
    placeholder: "Enter a catchy blog title",
  },
  {
    options: [],
    required: true,
    type: "select",
    name: "categoryId",
    label: "Blog Category",
    placeholder: "Select a category for this blog",
  },
  {
    type: "choose",
    name: "isActive",
    label: "Publish Status",
    placeholder: "Choose whether to publish this blog",
  },
  {
    rows: 5,
    type: "textarea",
    name: "short_description",
    label: "Short Description",
    placeholder: "Write a short summary (max 250 characters)",
    required: true,
  },
  {
    type: "file",
    required: true,
    name: "imageUrl",
    label: "Cover Image",
    placeholder: "Upload the blog cover image",
    accept: "image/*",
  },
  {
    rows: 1,
    required: true,
    widthFull: true,
    name: "description",
    label: "Full Blog Content",
    type: "richTextEditor",
    placeholder: "Write your blog content here...",
  },
];

export const brandFields: FormField[] = [
  {
    name: "name.en",
    label: "Brand Name (EN)",
    placeholder: "Enter brand name in English",
    type: "text",
    required: true,
    maxLength: 100,
  },
  {
    name: "name.ar",
    label: "Brand Name (AR)",
    placeholder: "أدخل اسم العلامة التجارية باللغة العربية",
    type: "text",
    required: true,
    maxLength: 100,
  },
  {
    name: "country.en",
    label: "Country (EN)",
    type: "text",
    placeholder: "Enter country in English",
    required: false,
  },
  {
    name: "country.ar",
    label: "Country (AR)",
    type: "text",
    placeholder: "أدخل اسم الدولة باللغة العربية",
    required: false,
  },
  {
    name: "establishedYear",
    label: "Established Year",
    type: "number",
    placeholder: "Enter the year brand was established (e.g. 1949)",
    required: false,
    min: 1800,
    max: new Date().getFullYear(),
  },
  {
    name: "isActive",
    label: "Active Status",
    type: "choose", // boolean field
    required: true,
    options: [
      { label: "Active", value: true },
      { label: "Inactive", value: false },
    ],
  },
  {
    name: "description.en",
    label: "Description (EN)",
    type: "textarea",
    rows: 1,
    widthFull: true,
    placeholder: "Write a short description in English",
    required: false,
    maxLength: 250,
  },
  {
    name: "description.ar",
    label: "Description (AR)",
    type: "textarea",
    rows: 7,
    placeholder: "اكتب وصفًا قصيرًا باللغة العربية",
    required: false,
    maxLength: 250,
  },
  {
    name: "imageUrl",
    label: "Logo / Image",
    type: "file",
    placeholder: "Upload Brand Logo or Image",
    required: false,
    accept: "image/*",
  },
];

export const categoryField: FormField[] = [
  {
    name: "name",
    label: "Category Name",
    type: "text",
    required: true,
    maxLength: 50,
    minLength: 2,
    placeholder: "Enter the category name (e.g., Technology, Lifestyle)",
  },
  {
    name: "type",
    label: "Category Type",
    type: "text",
    required: true,
    placeholder: "Specify the type (e.g., Blog, Product, Service)",
  },
  {
    type: "choose",
    name: "isActive",
    label: "Category Status",
    placeholder: "Select whether the category is active",
  },
  {
    rows: 2,
    widthFull: true,
    name: "description",
    label: "Category Description",
    type: "textarea",
    maxLength: 200,
    placeholder: "Provide a short description of the category",
  },
];

export const productcategoryType: FormField[] = [
  {
    type: "text",
    name: "name.en",
    required: true,
    label: "Category Name (EN)",
    placeholder: "Enter category name in English",
    rows: 1,
    maxLength: 50,
  },
  {
    type: "text",
    name: "name.ar",
    required: true,
    label: "Category Name (AR)",
    placeholder: "أدخل اسم الفئة باللغة العربية",
    rows: 1,
    maxLength: 50,
  },
  {
    type: "select",
    name: "parentCategory",
    label: "Select Parent Category",
    placeholder: "Select Parent Category",
    options: [], // dynamically populated
  },
  {
    type: "choose",
    name: "status",
    label: "Activate Product Category?",
    required: true,
    options: [
      { label: "Active", value: true },
      { label: "Inactive", value: false },
    ],
  },
  {
    type: "textarea",
    name: "description.en",
    required: true,
    label: "Category Description (EN)",
    placeholder:
      "Briefly describe the category, e.g. 'Devices like laptops, desktops, and accessories for tech enthusiasts'",
    rows: 1,
    maxLength: 100,
    widthFull: true,
  },
  {
    type: "textarea",
    name: "description.ar",
    required: true,
    label: "Category Description (AR)",
    placeholder:
      "صف الفئة بإيجاز، مثل 'أجهزة مثل أجهزة الكمبيوتر المحمولة وأجهزة الكمبيوتر المكتبية والملحقات لعشاق التقنية'",
    rows: 1,
    maxLength: 100,
    widthFull: true,
  },
];

export const categoryType: FormField[] = [
  {
    rows: 1,
    name: "name",
    type: "text",
    maxLength: 50,
    required: true,
    label: "Category Name",
    placeholder: "Enter parent or sub-category name",
  },
  {
    options: [],
    type: "select",
    name: "parentCategory",
    label: "Select Parent Category",
    placeholder: "Select Parent Category",
  },
  {
    name: "status",
    label: "Activate Product Category?",
    type: "choose",
    required: true,
  },
  {
    rows: 5,
    required: true,
    maxLength: 100,
    widthFull: true,
    type: "textarea",
    name: "description",
    label: "Category Description",
    placeholder:
      "Briefly describe the category, e.g. 'Devices like laptops, desktops, and accessories for tech enthusiasts'",
  },
];

export const groundField: FormField[] = [
  {
    options: [],
    name: "userId",
    label: "Ground Owner",
    type: "select",
    required: true,
    placeholder: "Select the owner of this property",
  },
  {
    name: "name.en",
    label: "Ground Name (EN)",
    type: "text",
    placeholder: "Enter ground name in English",
    required: true,
    maxLength: 150,
  },
  {
    name: "name.ar",
    label: "Ground Name (AR)",
    type: "text",
    placeholder: "أدخل اسم الملعب باللغة العربية",
    required: true,
    maxLength: 150,
  },
  {
    name: "type.en",
    type: "select",
    required: true,
    label: "Ground Type (EN)",
    options: [
      { label: "Tennis", value: "Tennis" },
      { label: "Hockey", value: "Hockey" },
      { label: "Cricket", value: "Cricket" },
      { label: "Football", value: "Football" },
      { label: "Badminton", value: "Badminton" },
      { label: "Volleyball", value: "Volleyball" },
    ],
    placeholder: "Select Ground Type (EN)",
  },
  {
    name: "type.ar",
    type: "select",
    required: true,
    label: "نوع الملعب (AR)",
    options: [
      { label: "تنس", value: "تنس" },
      { label: "هوكي", value: "هوكي" },
      { label: "كريكيت", value: "كريكيت" },
      { label: "كرة القدم", value: "كرة القدم" },
      { label: "بادمينتون", value: "بادمينتون" },
      { label: "كرة الطائرة", value: "كرة الطائرة" },
    ],
    placeholder: "اختر نوع الملعب (AR)",
  },
  {
    name: "pitchType.en",
    type: "select",
    required: true,
    label: "Pitch Type (EN)",
    options: [
      { label: "Natural Grass", value: "Natural Grass" },
      { label: "Artificial Turf", value: "Artificial Turf" },
      { label: "Hybrid Grass (Natural + Synthetic)", value: "Hybrid Grass" },
      { label: "Clay Court", value: "Clay Court" },
      { label: "Hard Court (Asphalt/Concrete)", value: "Hard Court" },
      { label: "Acrylic Court", value: "Acrylic Court" },
      { label: "Carpet Court", value: "Carpet Court" },
      { label: "Sand Pitch", value: "Sand Pitch" },
      { label: "Wooden Court", value: "Wooden Court" },
      { label: "AstroTurf (Hockey Specific)", value: "AstroTurf" },
      { label: "Indoor Synthetic Flooring", value: "Indoor Synthetic" },
      { label: "Matting Pitch (Cricket)", value: "Matting Pitch" },
      { label: "Coconut Matting (Traditional Cricket)", value: "Coconut Matting" },
      { label: "Red Soil Pitch", value: "Red Soil Pitch" },
      { label: "Black Soil Pitch", value: "Black Soil Pitch" },
      { label: "Multi-Sport Modular Tiles", value: "Modular Tiles" },
    ],
    placeholder: "Select Pitch Type (EN)",
  },
  {
    name: "pitchType.ar",
    type: "select",
    required: true,
    label: "نوع أرضية الملعب (AR)",
    options: [
      { label: "عشب طبيعي", value: "عشب طبيعي" },
      { label: "عشب صناعي", value: "عشب صناعي" },
      { label: "عشب هجين (طبيعي + صناعي)", value: "عشب هجين" },
      { label: "ملعب طيني", value: "ملعب طيني" },
      { label: "ملعب صلب (أسفلت/خرسانة)", value: "ملعب صلب" },
      { label: "ملعب أكريليك", value: "ملعب أكريليك" },
      { label: "ملعب سجاد", value: "ملعب سجاد" },
      { label: "ملعب رملي", value: "ملعب رملي" },
      { label: "ملعب خشبي", value: "ملعب خشبي" },
      { label: "عشب صناعي خاص بالهوكي (AstroTurf)", value: "AstroTurf" },
      { label: "أرضية صناعية داخلية", value: "أرضية صناعية داخلية" },
      { label: "ملعب حصير (كريكيت)", value: "ملعب حصير" },
      { label: "حصير جوز الهند (كريكيت تقليدي)", value: "حصير جوز الهند" },
      { label: "ملعب تربة حمراء", value: "ملعب تربة حمراء" },
      { label: "ملعب تربة سوداء", value: "ملعب تربة سوداء" },
      { label: "أرضية متعددة الرياضات (بلاط)", value: "بلاط متعدد الرياضات" },
    ],
    placeholder: "اختر نوع أرضية الملعب (AR)",
  },
  {
    name: "status",
    label: "Ground Status",
    type: "select",
    required: true,
    options: [
      { label: "active", value: "Active" },
      { label: "inactive", value: "In Active" },
      { label: "maintenance", value: "Under Maintenance" },
    ],
    placeholder: "Select availability status",
  },
  {
    type: "time",
    required: true,
    name: "startTime",
    label: "Start Time",
    placeholder: "Select Start Time",
  },
  {
    type: "time",
    required: true,
    name: "endTime",
    label: "End Time",
    placeholder: "Select End Time",
  },
  {
    type: "number",
    required: true,
    name: "pricePerHour",
    label: "Rental Price (SAR/hour)",
    placeholder: "Enter price per hour",
  },
  {
    name: "latitude",
    label: "Latitude",
    type: "text",
    required: true,
    placeholder: "Enter latitude (e.g., 28.7041)",
  },
  {
    name: "longitude",
    label: "Longitude",
    type: "text",
    required: true,
    placeholder: "Enter longitude (e.g., 77.1025)",
  },
  {
    rows: 1,
    required: true,
    widthFull: true,
    name: "address.en",
    type: "textarea",
    label: "Ground Address (EN)",
    placeholder: "Enter full address of the ground in English",
  },
  {
    rows: 1,
    required: true,
    widthFull: true,
    name: "address.ar",
    type: "textarea",
    label: "عنوان الملعب (AR)",
    placeholder: "أدخل العنوان الكامل للملعب باللغة العربية",
  },
  {
    rows: 2,
    widthFull: true,
    required: true,
    type: "textarea",
    name: "description.en",
    label: "Ground Description (EN)",
    placeholder: "Provide additional details about the ground in English (optional)",
  },
  {
    rows: 2,
    required: true,
    type: "textarea",
    widthFull: true,
    name: "description.ar",
    label: "وصف الملعب (AR)",
    placeholder: "أدخل تفاصيل إضافية عن الملعب باللغة العربية (اختياري)",
  },
  // {
  //   name: "facilities",
  //   label: "Available Facilities",
  //   type: "select",
  //   isMultiple: true,
  //   required: false,
  //   options: [
  //     // Basic Amenities
  //     { label: "Parking", value: "Parking" },
  //     { label: "Washroom/Restrooms", value: "Washroom/Restrooms" },
  //     { label: "Floodlights", value: "Floodlights" },
  //     { label: "Seating Area", value: "Seating Area" },
  //     { label: "Changing Rooms", value: "Changing Rooms" },
  //     { label: "Referee Room", value: "Referee Room" },
  //     { label: "First Aid Station", value: "First Aid Station" },
  //     { label: "Canteen/Refreshments", value: "Canteen/Refreshments" },
  //     { label: "Equipment Storage", value: "Equipment Storage" },

  //     // Advanced Technology & Infrastructure
  //     { label: "LED Scoreboard", value: "LED Scoreboard" },
  //     { label: "Digital Display Screens", value: "Digital Display Screens" },
  //     { label: "Stadium Wi-Fi Network", value: "Stadium Wi-Fi Network" },
  //     { label: "5G Connectivity", value: "5G Connectivity" },
  //     {
  //       label: "PA System with Zone Control",
  //       value: "PA System with Zone Control",
  //     },
  //     { label: "Video Analysis Room", value: "Video Analysis Room" },
  //     { label: "Live Streaming Setup", value: "Live Streaming Setup" },
  //     {
  //       label: "CCTV with Facial Recognition",
  //       value: "CCTV with Facial Recognition",
  //     },
  //     { label: "Access Control System", value: "Access Control System" },
  //     { label: "RFID Turnstiles", value: "RFID Turnstiles" },
  //     { label: "Biometric Entry System", value: "Biometric Entry System" },
  //     { label: "Smart Parking System", value: "Smart Parking System" },

  //     // Premium Facilities
  //     { label: "VIP Lounge", value: "VIP Lounge" },
  //     { label: "Corporate Boxes", value: "Corporate Boxes" },
  //     { label: "Executive Suites", value: "Executive Suites" },
  //     { label: "Premium Seating", value: "Premium Seating" },
  //     { label: "Hospitality Areas", value: "Hospitality Areas" },
  //     { label: "Private Dining Rooms", value: "Private Dining Rooms" },
  //     { label: "Conference Rooms", value: "Conference Rooms" },
  //     { label: "Business Center", value: "Business Center" },
  //     { label: "Rooftop Terrace", value: "Rooftop Terrace" },

  //     // Media & Broadcasting
  //     { label: "Media Box", value: "Media Box" },
  //     { label: "Press Conference Room", value: "Press Conference Room" },
  //     { label: "Broadcast Control Room", value: "Broadcast Control Room" },
  //     { label: "Commentary Boxes", value: "Commentary Boxes" },
  //     { label: "Camera Platforms", value: "Camera Platforms" },
  //     { label: "Satellite Uplink", value: "Satellite Uplink" },
  //     { label: "Radio Broadcasting Booth", value: "Radio Broadcasting Booth" },
  //     { label: "Interview Areas", value: "Interview Areas" },

  //     // Player Facilities
  //     { label: "Players' Lounge", value: "Players' Lounge" },
  //     { label: "Recovery/Ice Bath Room", value: "Recovery/Ice Bath Room" },
  //     { label: "Physiotherapy Center", value: "Physiotherapy Center" },
  //     { label: "Gym/Fitness Center", value: "Gym/Fitness Center" },
  //     { label: "Hydrotherapy Pool", value: "Hydrotherapy Pool" },
  //     { label: "Massage Rooms", value: "Massage Rooms" },
  //     { label: "Nutrition Center", value: "Nutrition Center" },
  //     { label: "Team Meeting Rooms", value: "Team Meeting Rooms" },
  //     { label: "Video Analysis Suites", value: "Video Analysis Suites" },
  //     { label: "Equipment Drying Room", value: "Equipment Drying Room" },

  //     // Medical & Safety
  //     { label: "Medical Room", value: "Medical Room" },
  //     { label: "Ambulance Bay", value: "Ambulance Bay" },
  //     {
  //       label: "Emergency Response Center",
  //       value: "Emergency Response Center",
  //     },
  //     { label: "Defibrillator Stations", value: "Defibrillator Stations" },
  //     { label: "Fire Safety System", value: "Fire Safety System" },
  //     { label: "Emergency Exits", value: "Emergency Exits" },
  //     { label: "Evacuation Routes", value: "Evacuation Routes" },
  //     { label: "Security Command Center", value: "Security Command Center" },

  //     // Field & Technical
  //     { label: "Hybrid Grass System", value: "Hybrid Grass System" },
  //     { label: "Undersoil Heating", value: "Undersoil Heating" },
  //     { label: "Advanced Irrigation", value: "Advanced Irrigation" },
  //     { label: "Drainage System", value: "Drainage System" },
  //     { label: "Goal-Line Technology", value: "Goal-Line Technology" },
  //     { label: "VAR Room", value: "VAR Room" },
  //     { label: "LED Perimeter Boards", value: "LED Perimeter Boards" },
  //     { label: "Retractable Roof", value: "Retractable Roof" },
  //     { label: "Climate Control System", value: "Climate Control System" },
  //     { label: "Pitch Covers", value: "Pitch Covers" },

  //     // Spectator Experience
  //     { label: "Fan Zone", value: "Fan Zone" },
  //     { label: "Kids Play Area", value: "Kids Play Area" },
  //     { label: "Interactive Museum", value: "Interactive Museum" },
  //     { label: "Merchandise Megastore", value: "Merchandise Megastore" },
  //     { label: "Food Courts", value: "Food Courts" },
  //     { label: "Craft Beer Garden", value: "Craft Beer Garden" },
  //     { label: "Mobile Charging Stations", value: "Mobile Charging Stations" },
  //     { label: "Digital Concierge", value: "Digital Concierge" },
  //     { label: "Mobile App Integration", value: "Mobile App Integration" },
  //     { label: "Contactless Payments", value: "Contactless Payments" },

  //     // Sustainability & Environment
  //     { label: "Solar Power System", value: "Solar Power System" },
  //     { label: "Rainwater Harvesting", value: "Rainwater Harvesting" },
  //     { label: "Waste Management System", value: "Waste Management System" },
  //     { label: "LED Lighting System", value: "LED Lighting System" },
  //     { label: "Green Roof Technology", value: "Green Roof Technology" },
  //     {
  //       label: "Electric Vehicle Charging",
  //       value: "Electric Vehicle Charging",
  //     },
  //     { label: "Water Recycling Plant", value: "Water Recycling Plant" },
  //     { label: "Carbon Neutral Systems", value: "Carbon Neutral Systems" },

  //     // Additional Advanced Features
  //     { label: "Helicopter Landing Pad", value: "Helicopter Landing Pad" },
  //     { label: "Underground Tunnels", value: "Underground Tunnels" },
  //     {
  //       label: "Multi-Purpose Event Space",
  //       value: "Multi-Purpose Event Space",
  //     },
  //     { label: "Hotel/Accommodation", value: "Hotel/Accommodation" },
  //     { label: "Training Pitches", value: "Training Pitches" },
  //     { label: "Academy Facilities", value: "Academy Facilities" },
  //     { label: "Research Center", value: "Research Center" },
  //     { label: "Sports Science Lab", value: "Sports Science Lab" },
  //     { label: "Weather Station", value: "Weather Station" },
  //     { label: "Transport Hub", value: "Transport Hub" },
  //     { label: "Metro/Subway Connection", value: "Metro/Subway Connection" },
  //     { label: "Parking Automation", value: "Parking Automation" },
  //     { label: "Smart Toilets", value: "Smart Toilets" },
  //     { label: "Holographic Displays", value: "Holographic Displays" },
  //     { label: "AI-Powered Analytics", value: "AI-Powered Analytics" },
  //     { label: "Drone Surveillance", value: "Drone Surveillance" },
  //     {
  //       label: "Virtual Reality Experience",
  //       value: "Virtual Reality Experience",
  //     },
  //     {
  //       label: "Augmented Reality Features",
  //       value: "Augmented Reality Features",
  //     },
  //     { label: "Sound Dampening System", value: "Sound Dampening System" },
  //     { label: "Retractable Seating", value: "Retractable Seating" },
  //     {
  //       label: "Multi-Sport Configuration",
  //       value: "Multi-Sport Configuration",
  //     },
  //   ],
  //   placeholder: "Select facilities available at the ground",
  // },
  {
    name: "images",
    label: "Upload Ground Images",
    type: "file",
    widthFull: true,
    required: false,
    multiple: true,
    placeholder: "Upload multiple images (JPG, PNG, max 5MB each)",
    accept: "image/*",
  },
];
